---

- name: Check that the shell_setup file exists
  ansible.builtin.stat:
    path: "{{ myconf_dir }}/shell_setup.sh"
  register: common_shell_setup_file
  become: true

- name: Configure zsh shell, oh-my-zsh and tmux
  when: not common_shell_setup_file.stat.exists
  become: "{{ 'true' if 'root' == username else 'false' }}"
  block:
    - name: Create shell_setup.sh using template
      ansible.builtin.template:
        src: shell_setup.j2
        dest: "{{ myconf_dir }}/shell_setup.sh"
        mode: '0755'
        group: "{{ username }}"
        owner: "{{ usergroup }}"

    - name: Copy all files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ myconf_dir }}/"
        mode: '0755'
        group: "{{ username }}"
        owner: "{{ usergroup }}"
      with_fileglob: "{{ role_path }}/files/myconf/*"

    - name: Running shell_setup.sh
      ansible.builtin.command: "{{ myconf_dir }}/shell_setup.sh"
      args:
        chdir: "{{ myconf_dir }}"
      register: common_my_output
      changed_when: common_my_output.rc != 0

    - name: Set zsh as default shell
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/zsh
