---

- name: Check if oh-my-zsh dir exists
  ansible.builtin.shell: "ls -ap {{ home_dir }} | grep -E '.oh-my-zsh/'"
  become: true
  register: out
  changed_when: false
  ignore_errors: true
  tags: common_omyzsh

# - name: Print out
#   ansible.builtin.debug:
#     var: out.failed
#   tags: common_omyzsh

- name: Configure zsh shell, oh-my-zsh and tmux
  when: out.failed
  become: "{{ 'true' if 'root' == username else 'false' }}"
  block:
    - name: Create shell_setup.sh using template
      ansible.builtin.template:
        src: shell_setup.j2
        dest: "{{ myconf_dir }}/shell_setup.sh"
        mode: '0755'
        group: "{{ username }}"
        owner: "{{ usergroup }}"

    - name: Copy all files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ myconf_dir }}/"
        mode: '0755'
        group: "{{ username }}"
        owner: "{{ usergroup }}"
      with_fileglob: "{{ role_path }}/files/myconf/*"

    - name: Running shell_setup.sh
      ansible.builtin.command: "{{ myconf_dir }}/shell_setup.sh"
      args:
        chdir: "{{ myconf_dir }}"
      register: common_my_output
      changed_when: common_my_output.rc != 0

    - name: Set zsh as default shell
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/zsh
